databases:
  - name: postgres
    ipAllowList: []
    databaseName: employee_onboarding_portal_production
    user: employee_onboarding_portal_production

services:
  - type: web
    name: employee_onboarding_portal_production
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
