default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: developer
  password: developer
  host: <%= ENV.fetch("DB_HOST") { 'localhost' }%>
  port: 5432

development:
  <<: *default
  database: employee_onboarding_portal_development

test:
  <<: *default
  database: employee_onboarding_portal_test

production:
  <<: *default
  database: employee_onboarding_portal_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432
  pool: 10
